# <font color=blue> Bag of Words Representation </font>

## BOW Representation using Scikit-learn's CountVectorizer
Text preprocessing, tokenizing and the ability to filter out stopwords are all included in [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html), which builds a dictionary of features and transforms documents to feature vectors.

## Scikit-learn's CountVectorizer Methods

<table>
<tr><td>`fit(raw_documents[, y])`</td><td>Learn a vocabulary dictionary of all tokens in the raw documents.</td></tr>
<tr><td>`transform(raw_documents)`</td><td>Transform documents to document-term matrix.</td></tr>
<tr><td>`fit_transform(raw_documents[, y])`</td><td>Learn the vocabulary dictionary and return document-term matrix.</td></tr>
<tr><td>`get_feature_names_out([input_features])`</td><td>Get output feature names for transformation.</td></tr>
<tr><td>`vocabulary_`</td><td>A dictionary where keys are terms and values are indices in the feature matrix.</td></tr>

</table>

In [1]:
import spacy

nlp = spacy.load('en_core_web_sm')

In [2]:
corpus = [
    'i like this film',
    'the film parasite is an excellent film',
    'bong is an excellent director',
    'i would give this film five out of five stars'
]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cv = CountVectorizer()

In [5]:
# Transform the documents into a bag-of-words representation
corpus_cv = cv.fit_transform(corpus)
corpus_cv

<4x16 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [6]:
print(corpus_cv.toarray())

[[0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0]
 [1 0 0 1 2 0 0 1 0 0 0 1 0 1 0 0]
 [1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 2 1 0 0 1 1 0 1 0 1 1]]


In [7]:
cv.get_feature_names_out()

array(['an', 'bong', 'director', 'excellent', 'film', 'five', 'give',
       'is', 'like', 'of', 'out', 'parasite', 'stars', 'the', 'this',
       'would'], dtype=object)

In [8]:
# Convert a bag-of-words representation to an array
import pandas as pd

df = pd.DataFrame(corpus_cv.toarray(), columns = cv.get_feature_names_out())
print(df)

   an  bong  director  excellent  film  five  give  is  like  of  out  \
0   0     0         0          0     1     0     0   0     1   0    0   
1   1     0         0          1     2     0     0   1     0   0    0   
2   1     1         1          1     0     0     0   1     0   0    0   
3   0     0         0          0     1     2     1   0     0   1    1   

   parasite  stars  the  this  would  
0         0      0    0     1      0  
1         1      0    1     0      0  
2         0      0    0     0      0  
3         0      1    0     1      1  


---
## Let's Revisit the Movie Review Example
>- <font color = green> preprocess </font>
>- <font color = green> remove 'five' from the stop word list </font>

In [ ]:
# Remove the word from the set of stop words
nlp.Defaults.stop_words.remove('five')

nlp.vocab['five'].is_stop = False

In [ ]:
nlp.vocab['five'].is_stop

False

In [10]:
# Preprocess

def preprocess(doc):
    doc = nlp(doc)

    preprocessed_tokens = []
    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        else:
            preprocessed_tokens.append(token.lemma_)
    return " ".join(preprocessed_tokens)

In [11]:
preprocessed_corpus = [preprocess(d) for d in corpus]
print(preprocessed_corpus)

['like film', 'film parasite excellent film', 'bong excellent director', 'film star']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [ ]:
corpus_cv = cv.fit_transform(preprocessed_corpus)
corpus_cv

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [12]:
corpus_cv.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1]])

In [ ]:
cv.get_feature_names_out()

array(['bong', 'director', 'excellent', 'film', 'five', 'like',
       'parasite', 'star'], dtype=object)

In [ ]:
import pandas as pd
bow_df = pd.DataFrame(corpus_cv.toarray(), columns = cv.get_feature_names_out())
print(bow_df)

   bong  director  excellent  film  five  like  parasite  star
0     0         0          0     1     0     1         0     0
1     0         0          1     2     0     0         1     0
2     1         1          1     0     0     0         0     0
3     0         0          0     1     2     0         0     1


---
# <font color=blue> Stop Words </font>

Words like "a" and "the" appear so frequently that they don't require tagging as thoroughly as nouns, verbs and modifiers. We call these *stop words*, and they can be filtered from the text to be processed. spaCy holds a built-in list of some 305 English stop words.

In [ ]:
import spacy

nlp = spacy.load('en_core_web_sm')

In [ ]:
# Print the set of spaCy's default stop words (remember that sets are unordered):
print(nlp.Defaults.stop_words)

{'here', 'too', 'move', 'wherever', 'many', 'seem', 'when', 'to', 'i', 'some', 'yet', 'from', 'fifty', 'now', 'his', 'seeming', 'made', 'where', 'formerly', 'various', 'along', 'nine', 'become', 'after', 'themselves', 'every', 'everywhere', 'other', 'except', 'anyone', 'used', 'none', 'everything', 'have', "'re", 'be', 'much', "'m", 'somewhere', 'per', 'which', 'once', 'first', 'is', 'such', 'show', 'something', 'it', 'part', 'yourselves', 'whoever', 'each', 'mine', 'hereafter', 'latter', 'among', 'less', 'either', 'during', 'below', 'in', 'see', 'did', 'former', 'beyond', 'until', 'forty', 'at', 'indeed', 'for', '‘s', '‘ve', 'regarding', 'whether', 'or', 'somehow', 'since', 'beforehand', 'twelve', 'both', '’d', 'seemed', 'done', 'are', 'quite', 'off', 'side', 'herself', 'n‘t', 'her', 'take', 'perhaps', 'often', 'besides', 'two', 'without', 'towards', 'if', 'on', 'neither', 'has', 'these', 'do', 'they', 'whatever', 'could', 'our', 'thus', 'together', 'though', 'ten', 'noone', 'he', 'be

In [ ]:
len(nlp.Defaults.stop_words)

326

## To see if a word is a stop word

In [ ]:
nlp.vocab['is'].is_stop

True

In [ ]:
nlp.vocab['covid'].is_stop

False

## To add a stop word
There may be times when you wish to add a stop word to the default set. Perhaps you decide that `'btw'` (common shorthand for "by the way") should be considered a stop word.

In [ ]:
# Add the word to the set of stop words. Use lowercase!
nlp.Defaults.stop_words.add('btw')

nlp.vocab['btw'].is_stop = True

In [ ]:
len(nlp.Defaults.stop_words)

327

In [ ]:
nlp.vocab['btw'].is_stop

True

## To remove a stop word

You may decide that `'beyond'` should not be considered a stop word.

In [ ]:
# Remove the word from the set of stop words
nlp.Defaults.stop_words.remove('beyond')

nlp.vocab['beyond'].is_stop = False

In [ ]:
len(nlp.Defaults.stop_words)

326

In [ ]:
nlp.vocab['beyond'].is_stop

False

---
# <font color=blue> Running Example: Trump Tweets </font>

- Pre-processing the text
- BOW Representation

<font color=green> Step 1. Pre-processing </font>

In [ ]:
tweets_trump = [
    'First Vaccine Administered. Congratulations USA! Congratulations WORLD!',
    'People working in the White House should receive the vaccine somewhat later in the program, unless specifically necessary. I have asked that this adjustment be made. I am not scheduled to take the vaccine, but look forward to doing so at the appropriate time. Thank you!',
    'Until Noverber 4th., Fake News Media is going full on Covid, Covid, Covid. We are rounding the turn, 99.9%'
]

In [ ]:
# Get Lowercase Tweet
tweets_trump = [tweet.lower() for tweet in tweets_trump]
print(tweets_trump)

['first vaccine administered. congratulations usa! congratulations world!', 'people working in the white house should receive the vaccine somewhat later in the program, unless specifically necessary. i have asked that this adjustment be made. i am not scheduled to take the vaccine, but look forward to doing so at the appropriate time. thank you!', 'until noverber 4th., fake news media is going full on covid, covid, covid. we are rounding the turn, 99.9%']


In [ ]:
def preprocess(doc):
    doc = nlp(doc)

    preprocessed_tokens = []
    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        else:
            preprocessed_tokens.append(token.lemma_)
    return " ".join(preprocessed_tokens)

In [ ]:
# Apply preprocess to each tweet
preprocessed_tweets = [preprocess(t) for t in tweets_trump]
print(preprocessed_tweets)

['vaccine administer congratulation usa congratulation world', 'people work white house receive vaccine somewhat later program specifically necessary ask adjustment schedule vaccine look forward appropriate time thank', 'noverber 4th fake news medium go covid covid covid round turn 99.9']


<font color=green> Step 2. BOW Representation </font>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [ ]:
# Transform the documents into a bag-of-words representation
tweets_cv = cv.fit_transform(preprocessed_tweets)
tweets_cv

<3x33 sparse matrix of type '<class 'numpy.int64'>'
	with 34 stored elements in Compressed Sparse Row format>

In [ ]:
print(tweets_cv.toarray())

[[0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1]
 [0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 2 1 1 0]
 [1 1 0 0 0 0 0 3 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]]


In [ ]:
print(cv.get_feature_names_out())

['4th' '99' 'adjustment' 'administer' 'appropriate' 'ask' 'congratulation'
 'covid' 'fake' 'forward' 'go' 'house' 'later' 'look' 'medium' 'necessary'
 'news' 'noverber' 'people' 'program' 'receive' 'round' 'schedule'
 'somewhat' 'specifically' 'thank' 'time' 'turn' 'usa' 'vaccine' 'white'
 'work' 'world']


In [ ]:
# Create BOW Representation Dataframe
import pandas as pd
df = pd.DataFrame(tweets_cv.toarray(), columns = cv.get_feature_names_out())
print(df)

   4th  99  adjustment  administer  appropriate  ask  congratulation  covid  \
0    0   0           0           1            0    0               2      0   
1    0   0           1           0            1    1               0      0   
2    1   1           0           0            0    0               0      3   

   fake  forward  ...  somewhat  specifically  thank  time  turn  usa  \
0     0        0  ...         0             0      0     0     0    1   
1     0        1  ...         1             1      1     1     0    0   
2     1        0  ...         0             0      0     0     1    0   

   vaccine  white  work  world  
0        1      0     0      1  
1        2      1     1      0  
2        0      0     0      0  

[3 rows x 33 columns]
